---
# tasks file for ansible-role-rpi-hdmi-webcam

- name: Disable swap service
  become: yes
  service:
    name: dphys-swapfile.service
    state: stopped
    enabled: no

- name: Create /etc/systemd/system/camera.start.service from template
  become: yes
  template:
    src: etc/systemd/system/camera.start.service.j2
    dest: /etc/systemd/system/camera.start.service
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart camera.start

- name: Create /etc/systemd/system/webcam.start.service from template
  become: yes
  template:
    src: etc/systemd/system/webcam.start.service.j2
    dest: /etc/systemd/system/webcam.start.service
    owner: root
    group: root
    mode: 0644
#  notify:
#    - Restart webcam.start

- name: Disable webcam service
  become: yes
  service:
    name: webcam.start.service
    daemon_reload: yes
    state: stopped
    enabled: no

- name: Enable camera service
  become: yes
  service:
    name: camera.start.service
    daemon_reload: yes
    state: started
    enabled: yes

- name: Ensure camera gets restarted if average load on system gets too high - this is a workaround for current buggy behaviour
  ansible.builtin.cron:
    name: "Restart camera on high load"
    minute: "3"
    hour: "*"
    job: "test $(cat /proc/loadavg | cut -d"." -f1) -ge 2 && systemctl restart camera.start"
