---
# tasks file for ansible-role-rpi-hdmi-webcam

- name: Disable swap service
  service:
    name: dphys-swapfile.service
    state: stopped
    enabled: no

- name: Create /etc/systemd/system/camera.start.service from template
  template:
    src: etc/systemd/system/camera.start.service.j2
    dest: /etc/systemd/system/camera.start.service
    owner: root
    group: root
    mode: 0644
  notify:
    - 'restart camera.start'

- name: Create /etc/systemd/system/webcam.start.service from template
  template:
    src: etc/systemd/system/webcam.start.service.j2
    dest: /etc/systemd/system/webcam.start.service
    owner: root
    group: root
    mode: 0644
#  notify:
#    - 'restart webcam.start'

- name: Disable webcam service
  service:
    name: webcam.start.service
    state: stopped
    enabled: no

- name: Enable camera service
  service:
    name: camera.start.service
    state: started
    enabled: yes
