---
# handlers file for ansible-role-rpi-hdmi-webcam
- name: Restart camera.start
  service:
    name: camera.start
    state: restarted
    daemon_reload: yes

- name: Restart webcam.start
  service:
    name: webcam.start
    state: restarted
    daemon_reload: yes
